{% set name = "assembly_stats" %}
{% set version = "0.1.4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz"
  sha256: 5ef35e04b5d86acea839b04fcccd2a73e64e559ea31a8c256de8f0dda78e6968

build:
  number: 0
  noarch: python
  entry_points:
    - assembly_stats=assembly_stats.cli:cli
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - numpy
    - pip
    - python
  run:
    - numpy
    - python

test:
  imports:
    - assembly_stats
  commands:
    - assembly_stats -h

about:
  home: "https://github.com/MikeTrizna/assembly_stats"
  license: "MIT"
  license_family: "MIT"
  license_file: "LICENSE.md"
  summary: "Calculates both scaffold and contig statistics (N50, L50, etc.) from a scaffold FASTA file."
  doc_url: "https://github.com/MikeTrizna/assembly_stats"
  dev_url: "https://github.com/MikeTrizna/assembly_stats"

extra:
  recipe-maintainers:
    - MikeTrizna
