travis:
  secure:
    BINSTAR_TOKEN: SD4t43EuzpQfGD5gccWtYgHxzchteQmbew39xPpqmKTDtJJoIPjd8HL2iAc+vx4irueVClei6wzVm2pAuvTsoQ9+8UJHlOw2+inWkHyZ60YTn6bFchZ92sfJ8IkF0ti71EvbEOb6WIL2SQb8DSKB5UpwixFRbZQf4s8WIkZsRb2VMZViCTYGvKrk5ZomPjngPGx4na/UxNB6Q7DQCxmcJtNBkZnsFT/Z0lRLbrT0f258Bk3xGlczFBj3b7fyseT+44D7kz8+iylwZHepgWqgblffLHKz8jJ3igvjAlk1W/wHqTSqAxn4Q9J1zu/B1S1TaddyOIBlEU8tAU+lu/v/zEmtJSW6J66uX4lgI7FnbDX/ZL2iqdoVSdTYPCHOjuaN5myszdrxYEdhD8q6cBrelqw4pn4gzZ9lrcgNUXg6ELMmW5Umic91y+2e6orBxK9egE/oHYCLe0jNyLowEoCPDAjzi4jxTAq/8xqr71aeSlndAmuOOCCiTNp21vLzmNI0f92lK5Q+dk5HqQ8K0tQOv9gCYKEcNW3YRYfLOknqNZlOC0CFw9zPMOONgumQOA9W2FwtRmtp4mIku+I8Hfi9933fwxQuvatjugEA82rOGAOKkam05BnneH0U7+vvuFyUwX1G/lDcUkTCdW7y1CktXtfg4UYYrBa4VLS3feXQT84=
conda_forge_output_validation: true
github:
  branch_name: main
  tooling_branch_name: main
conda_build:
  pkg_format: '2'
